### ISSUE TITLE
TC-12: Explore option of using Atlasian BitBucket vs Amazon Aws

### ISSUE THREAD

**Issue by sbandaru-cpal** [sbandaru-cpal/coding-solutions#15]

**Comment by sbandaru-cpal** [comment]
estimate 4/26

**Comment by rrayapureddi-cpal** [comment]
https://confluence.atlassian.com/bitbucket/plans-and-billing-224395568.html

https://aws.amazon.com/free/

**Comment by rrayapureddi-cpal** [comment]
BitBucket is free for 5 users.
Amazon AWS is free for first 12 months only after that it is $1 to $3.
