### ISSUE TITLE
TC-6 Create Sales Tax Provider

### ISSUE THREAD

**Issue by sbandaru-cpal** [sbandaru-cpal/coding-solutions#6]
Create a Sales Tax Provider for Tax Calculator. 
Need to feed all the sales tax information as static information into Tax Calculator and this provider will give all the states with its sales tax.

Acceptance Criteria:
For a given amount return taxed total amount based on current selected state :ex $1000 in CA (state tax - 7.25) will return 1072.50

**Comment by sbandaru-cpal** [comment]
Estimation : 4/6

**Comment by rrayapureddi-cpal** [comment]
PR is created on 04/15

**Comment by rrayapureddi-cpal** [comment]
Code is merged
