### ISSUE TITLE
TC-8 Document Requirements for Tax Calculator for Version 1

### ISSUE THREAD

**Issue by sbandaru-cpal** [sbandaru-cpal/coding-solutions#8]
Document all the requirements for Tax Calculator version 1, create mockups for the version 1 ui

**Comment by vsak-cpal** [comment]
[TaxCal (1).docx](https://github.com/sbandaru-cpal/coding-solutions/files/1917021/TaxCal.1.docx)

Closing Requirements Card- Version 1
